[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"

[context.production.environment]
  HUGO_ENV = "production"

# Redirect old Netlify domain to custom domain
[[redirects]]
  from = "https://inxcribe.netlify.app/*"
  to = "https://inscribe.studio/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://inxcribe.netlify.app/*"
  to = "https://inscribe.studio/:splat"
  status = 301
  force = true