[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200